right_format = "$status"

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false

[git_metrics]
disabled = false

[memory_usage]
style = 'bold dimmed yellow'
disabled = false

[status]
format = '[$symbol $common_meaning$signal_name$maybe_int \[$status\]]($style) '
symbol = 'ó°…–'
disabled = false
