"$schema" = 'https://starship.rs/config-schema.json'

right_format = '$status'

[directory]
truncation_length = 5

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false

[memory_usage]
style = 'bold dimmed yellow'
disabled = false

[hostname]
ssh_symbol = 'ïˆ³  '

[git_metrics]
disabled = false

[status]
format = '[$symbol $common_meaning$signal_name$maybe_int \[$status\]]($style) '
symbol = 'ó°…–'
disabled = false

[[battery.display]]
threshold = 25

# Disabled modules
[gradle]
disabled = true

[kotlin]
disabled = true

[java]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true
